### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by chenxiemin** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#1]
Can you please help to provide a pretrained model for testing? sorry for asking the request in this manner.

**Comment by Fabian-Sc85** [comment]
Hi, I will be uploading some trained models ASAP

**Comment by Fabian-Sc85** [comment]
I have uploaded models trained on PPG data from the MIMIC-III database in the "trained_models" folders. I will update the README file accordingly

**Comment by zj2050** [comment]
> I have uploaded models trained on PPG data from the MIMIC-III database in the "trained_models" folders. I will update the README file accordingly

I can't find "trained_models" folders , can provide a linker?
