### ISSUE TITLE
Prediction using rPPG or PPG

### ISSUE THREAD

**Issue by gohjiayi** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#14]
Hi there, thank you for making your codes open-sourced.

Referring to the [Using the pretrained models](https://github.com/Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#using-the-pretrained-models) section in README, you mentioned the following:

> To use the networks for prediction/fine-tuning, input and output data must meet the following requirements:
> 
> input data must have a length of 875 samples (corresponds to 7 seconds using a sampling frequency of 125 Hz)
> SBP and DBP must be provided separately as there is one output node for each value

I am intending to use the model for predictions with my own rPPG or PPG data. However, should SBP and DBP be provided given that they are supposed to be the predicted output values? Also, do you have any additional insights on how I might be able to do so with my own data?

**Comment by Fabian-Sc85** [comment]
Hi, thanks for your interest. The description is indeed a bit misleading. PPG and BP data are only neccessary for finetuning the networks. During prediction, you only need to present (r)PPG data. You just need to use the `model.predict()` to predict BP based on your signals.
