### ISSUE TITLE
file's type does not match 

### ISSUE THREAD

**Issue by Songjingze** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#3]
hi,your code 'download_mimic_iii_records.py' seems to save code with 'h5py', but 'prepare_MIMIC_dataset.py' needs file ending in '.mat'.
'download_mimic_iii_records.py' line 103:
`        with h5py.File(join(SubjectFolder, file.split('/')[1]),'w') as f:   `

 'prepare_MIMIC_dataset.py' line line 79:
`DataFiles = [f for f in listdir(join(DataPath,dirs)) if isfile(join(DataPath, dirs,f)) and f.endswith('.mat')] `

**Comment by Fabian-Sc85** [comment]
Hi, thank you for pointing that out. I have resolved the issue. The scripts now work with h5-files only.

However, you can always use the preprocessed dataset available at [Zenodo](https://zenodo.org/record/5590603).
