### ISSUE TITLE
A valuable study

### ISSUE THREAD

**Issue by chuzheng88** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#7]
Hi, I have read your paper "Assessment of Non-Invasive Blood Pressure Prediction from PPG and rPPG Signals Using Deep Learning", and then your github project also was read. I think, your research is very valuable.  I read the sentens "The PPG dataset used for training the neural architectures and the trained models themselves can be found at Zenodo.", and then, I want to know that is the dataset at Zenodo the preprocessed by the script "download_mimic_iii_records.py", "prepare_MIMIC_dataset.py", "h5_to_tfrecord.py", or the original dataset ?

**Comment by Fabian-Sc85** [comment]
Hello, thank you for you interest in our work. The dataset that you can find at Zenodo is the one prepared by the script „prepare_MIMIC_dataset.py“. It contains the windowed PPG signals from each subject downloaded from the MIMIC-III database and the corresponding SBP and DBP values derived from the ABP signal windows.

**Comment by chuzheng88** [comment]
@Fabian-Sc85 thank you for your reply.
